name: Docker build & push

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
     steps:
       - name: checkout Repository
         uses: actions/checkout@v2

       - name: login to docker hub
         run: echo"${{ secrets.DOCKER_PASSWORD }}" | DOCKER LOGIN -u"${{ secrets.DOCKER_USERNAME }}" --password-stdin

       - name: buid docker image
         run: docker build -t dockwithvamsee/multi-container-app-web:latest .

       - name: push to docker hub
         run: docker push dockwithvamsee/multi-container-app-web:latest
